/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillGrowthRouteImport } from './routes/skill-growth'
import { Route as SkillGapRouteImport } from './routes/skill-gap'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SavedJobsRouteImport } from './routes/saved-jobs'
import { Route as SalaryInsightsRouteImport } from './routes/salary-insights'
import { Route as RoadmapGeneratorRouteImport } from './routes/roadmap-generator'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileCompletionRouteImport } from './routes/profile-completion'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlatformAnalyticsRouteImport } from './routes/platform-analytics'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InterviewPrepRouteImport } from './routes/interview-prep'
import { Route as IndustryDemandRouteImport } from './routes/industry-demand'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmployabilityRouteImport } from './routes/employability'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CourseProgressRouteImport } from './routes/course-progress'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CareerSuccessRouteImport } from './routes/career-success'
import { Route as CareerForecastingRouteImport } from './routes/career-forecasting'
import { Route as CareerDnaRouteImport } from './routes/career-dna'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AppliedJobsRouteImport } from './routes/applied-jobs'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SkillsTrendingRouteImport } from './routes/skills.trending'
import { Route as SkillsTimelineRouteImport } from './routes/skills.timeline'
import { Route as SkillsCategoriesRouteImport } from './routes/skills.categories'
import { Route as SkillsAssessmentRouteImport } from './routes/skills.assessment'
import { Route as SkillsAddRouteImport } from './routes/skills.add'
import { Route as SkillsSkillIdRouteImport } from './routes/skills.$skillId'
import { Route as SettingsThemeRouteImport } from './routes/settings.theme'
import { Route as SettingsSubscriptionRouteImport } from './routes/settings.subscription'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsLanguageRouteImport } from './routes/settings.language'
import { Route as SettingsAccountsRouteImport } from './routes/settings.accounts'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as LearningMyCoursesRouteImport } from './routes/learning.my-courses'
import { Route as JobJobIdRouteImport } from './routes/job.$jobId'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as CompanyCompanyIdRouteImport } from './routes/company.$companyId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const SkillGrowthRoute = SkillGrowthRouteImport.update({
  id: '/skill-growth',
  path: '/skill-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapRoute = SkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedJobsRoute = SavedJobsRouteImport.update({
  id: '/saved-jobs',
  path: '/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryInsightsRoute = SalaryInsightsRouteImport.update({
  id: '/salary-insights',
  path: '/salary-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapGeneratorRoute = RoadmapGeneratorRouteImport.update({
  id: '/roadmap-generator',
  path: '/roadmap-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCompletionRoute = ProfileCompletionRouteImport.update({
  id: '/profile-completion',
  path: '/profile-completion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAnalyticsRoute = PlatformAnalyticsRouteImport.update({
  id: '/platform-analytics',
  path: '/platform-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewPrepRoute = InterviewPrepRouteImport.update({
  id: '/interview-prep',
  path: '/interview-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryDemandRoute = IndustryDemandRouteImport.update({
  id: '/industry-demand',
  path: '/industry-demand',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployabilityRoute = EmployabilityRouteImport.update({
  id: '/employability',
  path: '/employability',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseProgressRoute = CourseProgressRouteImport.update({
  id: '/course-progress',
  path: '/course-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerSuccessRoute = CareerSuccessRouteImport.update({
  id: '/career-success',
  path: '/career-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerForecastingRoute = CareerForecastingRouteImport.update({
  id: '/career-forecasting',
  path: '/career-forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerDnaRoute = CareerDnaRouteImport.update({
  id: '/career-dna',
  path: '/career-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppliedJobsRoute = AppliedJobsRouteImport.update({
  id: '/applied-jobs',
  path: '/applied-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsTrendingRoute = SkillsTrendingRouteImport.update({
  id: '/skills/trending',
  path: '/skills/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsTimelineRoute = SkillsTimelineRouteImport.update({
  id: '/skills/timeline',
  path: '/skills/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsCategoriesRoute = SkillsCategoriesRouteImport.update({
  id: '/skills/categories',
  path: '/skills/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsAssessmentRoute = SkillsAssessmentRouteImport.update({
  id: '/skills/assessment',
  path: '/skills/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsAddRoute = SkillsAddRouteImport.update({
  id: '/skills/add',
  path: '/skills/add',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/settings/theme',
  path: '/settings/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: '/settings/subscription',
  path: '/settings/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/settings/language',
  path: '/settings/language',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountsRoute = SettingsAccountsRouteImport.update({
  id: '/settings/accounts',
  path: '/settings/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningMyCoursesRoute = LearningMyCoursesRouteImport.update({
  id: '/learning/my-courses',
  path: '/learning/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdRoute = JobJobIdRouteImport.update({
  id: '/job/$jobId',
  path: '/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdRoute = CompanyCompanyIdRouteImport.update({
  id: '/company/$companyId',
  path: '/company/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/applied-jobs': typeof AppliedJobsRoute
  '/assignments': typeof AssignmentsRoute
  '/career': typeof CareerRoute
  '/career-dna': typeof CareerDnaRoute
  '/career-forecasting': typeof CareerForecastingRoute
  '/career-success': typeof CareerSuccessRoute
  '/certificates': typeof CertificatesRoute
  '/course-progress': typeof CourseProgressRoute
  '/courses': typeof CoursesRoute
  '/employability': typeof EmployabilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/industry-demand': typeof IndustryDemandRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/platform-analytics': typeof PlatformAnalyticsRoute
  '/profile': typeof ProfileRoute
  '/profile-completion': typeof ProfileCompletionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap-generator': typeof RoadmapGeneratorRoute
  '/salary-insights': typeof SalaryInsightsRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/signup': typeof SignupRoute
  '/skill-gap': typeof SkillGapRoute
  '/skill-growth': typeof SkillGrowthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/learning/my-courses': typeof LearningMyCoursesRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/add': typeof SkillsAddRoute
  '/skills/assessment': typeof SkillsAssessmentRoute
  '/skills/categories': typeof SkillsCategoriesRoute
  '/skills/timeline': typeof SkillsTimelineRoute
  '/skills/trending': typeof SkillsTrendingRoute
  '/admin/': typeof AdminIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/applied-jobs': typeof AppliedJobsRoute
  '/assignments': typeof AssignmentsRoute
  '/career': typeof CareerRoute
  '/career-dna': typeof CareerDnaRoute
  '/career-forecasting': typeof CareerForecastingRoute
  '/career-success': typeof CareerSuccessRoute
  '/certificates': typeof CertificatesRoute
  '/course-progress': typeof CourseProgressRoute
  '/courses': typeof CoursesRoute
  '/employability': typeof EmployabilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/industry-demand': typeof IndustryDemandRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/platform-analytics': typeof PlatformAnalyticsRoute
  '/profile': typeof ProfileRoute
  '/profile-completion': typeof ProfileCompletionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap-generator': typeof RoadmapGeneratorRoute
  '/salary-insights': typeof SalaryInsightsRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/signup': typeof SignupRoute
  '/skill-gap': typeof SkillGapRoute
  '/skill-growth': typeof SkillGrowthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/learning/my-courses': typeof LearningMyCoursesRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/add': typeof SkillsAddRoute
  '/skills/assessment': typeof SkillsAssessmentRoute
  '/skills/categories': typeof SkillsCategoriesRoute
  '/skills/timeline': typeof SkillsTimelineRoute
  '/skills/trending': typeof SkillsTrendingRoute
  '/admin': typeof AdminIndexRoute
  '/skills': typeof SkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/applied-jobs': typeof AppliedJobsRoute
  '/assignments': typeof AssignmentsRoute
  '/career': typeof CareerRoute
  '/career-dna': typeof CareerDnaRoute
  '/career-forecasting': typeof CareerForecastingRoute
  '/career-success': typeof CareerSuccessRoute
  '/certificates': typeof CertificatesRoute
  '/course-progress': typeof CourseProgressRoute
  '/courses': typeof CoursesRoute
  '/employability': typeof EmployabilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/industry-demand': typeof IndustryDemandRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/platform-analytics': typeof PlatformAnalyticsRoute
  '/profile': typeof ProfileRoute
  '/profile-completion': typeof ProfileCompletionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap-generator': typeof RoadmapGeneratorRoute
  '/salary-insights': typeof SalaryInsightsRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/signup': typeof SignupRoute
  '/skill-gap': typeof SkillGapRoute
  '/skill-growth': typeof SkillGrowthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/learning/my-courses': typeof LearningMyCoursesRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/add': typeof SkillsAddRoute
  '/skills/assessment': typeof SkillsAssessmentRoute
  '/skills/categories': typeof SkillsCategoriesRoute
  '/skills/timeline': typeof SkillsTimelineRoute
  '/skills/trending': typeof SkillsTrendingRoute
  '/admin/': typeof AdminIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/applied-jobs'
    | '/assignments'
    | '/career'
    | '/career-dna'
    | '/career-forecasting'
    | '/career-success'
    | '/certificates'
    | '/course-progress'
    | '/courses'
    | '/employability'
    | '/forgot-password'
    | '/home'
    | '/industry-demand'
    | '/interview-prep'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/platform-analytics'
    | '/profile'
    | '/profile-completion'
    | '/reset-password'
    | '/roadmap-generator'
    | '/salary-insights'
    | '/saved-jobs'
    | '/signup'
    | '/skill-gap'
    | '/skill-growth'
    | '/admin/analytics'
    | '/admin/reports'
    | '/admin/users'
    | '/company/$companyId'
    | '/course/$courseId'
    | '/job/$jobId'
    | '/learning/my-courses'
    | '/lesson/$lessonId'
    | '/settings/account'
    | '/settings/accounts'
    | '/settings/language'
    | '/settings/privacy'
    | '/settings/security'
    | '/settings/subscription'
    | '/settings/theme'
    | '/skills/$skillId'
    | '/skills/add'
    | '/skills/assessment'
    | '/skills/categories'
    | '/skills/timeline'
    | '/skills/trending'
    | '/admin/'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/applied-jobs'
    | '/assignments'
    | '/career'
    | '/career-dna'
    | '/career-forecasting'
    | '/career-success'
    | '/certificates'
    | '/course-progress'
    | '/courses'
    | '/employability'
    | '/forgot-password'
    | '/home'
    | '/industry-demand'
    | '/interview-prep'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/platform-analytics'
    | '/profile'
    | '/profile-completion'
    | '/reset-password'
    | '/roadmap-generator'
    | '/salary-insights'
    | '/saved-jobs'
    | '/signup'
    | '/skill-gap'
    | '/skill-growth'
    | '/admin/analytics'
    | '/admin/reports'
    | '/admin/users'
    | '/company/$companyId'
    | '/course/$courseId'
    | '/job/$jobId'
    | '/learning/my-courses'
    | '/lesson/$lessonId'
    | '/settings/account'
    | '/settings/accounts'
    | '/settings/language'
    | '/settings/privacy'
    | '/settings/security'
    | '/settings/subscription'
    | '/settings/theme'
    | '/skills/$skillId'
    | '/skills/add'
    | '/skills/assessment'
    | '/skills/categories'
    | '/skills/timeline'
    | '/skills/trending'
    | '/admin'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/applied-jobs'
    | '/assignments'
    | '/career'
    | '/career-dna'
    | '/career-forecasting'
    | '/career-success'
    | '/certificates'
    | '/course-progress'
    | '/courses'
    | '/employability'
    | '/forgot-password'
    | '/home'
    | '/industry-demand'
    | '/interview-prep'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/platform-analytics'
    | '/profile'
    | '/profile-completion'
    | '/reset-password'
    | '/roadmap-generator'
    | '/salary-insights'
    | '/saved-jobs'
    | '/signup'
    | '/skill-gap'
    | '/skill-growth'
    | '/admin/analytics'
    | '/admin/reports'
    | '/admin/users'
    | '/company/$companyId'
    | '/course/$courseId'
    | '/job/$jobId'
    | '/learning/my-courses'
    | '/lesson/$lessonId'
    | '/settings/account'
    | '/settings/accounts'
    | '/settings/language'
    | '/settings/privacy'
    | '/settings/security'
    | '/settings/subscription'
    | '/settings/theme'
    | '/skills/$skillId'
    | '/skills/add'
    | '/skills/assessment'
    | '/skills/categories'
    | '/skills/timeline'
    | '/skills/trending'
    | '/admin/'
    | '/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AppliedJobsRoute: typeof AppliedJobsRoute
  AssignmentsRoute: typeof AssignmentsRoute
  CareerRoute: typeof CareerRoute
  CareerDnaRoute: typeof CareerDnaRoute
  CareerForecastingRoute: typeof CareerForecastingRoute
  CareerSuccessRoute: typeof CareerSuccessRoute
  CertificatesRoute: typeof CertificatesRoute
  CourseProgressRoute: typeof CourseProgressRoute
  CoursesRoute: typeof CoursesRoute
  EmployabilityRoute: typeof EmployabilityRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  IndustryDemandRoute: typeof IndustryDemandRoute
  InterviewPrepRoute: typeof InterviewPrepRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PlatformAnalyticsRoute: typeof PlatformAnalyticsRoute
  ProfileRoute: typeof ProfileRoute
  ProfileCompletionRoute: typeof ProfileCompletionRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapGeneratorRoute: typeof RoadmapGeneratorRoute
  SalaryInsightsRoute: typeof SalaryInsightsRoute
  SavedJobsRoute: typeof SavedJobsRoute
  SignupRoute: typeof SignupRoute
  SkillGapRoute: typeof SkillGapRoute
  SkillGrowthRoute: typeof SkillGrowthRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CompanyCompanyIdRoute: typeof CompanyCompanyIdRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  JobJobIdRoute: typeof JobJobIdRoute
  LearningMyCoursesRoute: typeof LearningMyCoursesRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAccountsRoute: typeof SettingsAccountsRoute
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  SkillsAddRoute: typeof SkillsAddRoute
  SkillsAssessmentRoute: typeof SkillsAssessmentRoute
  SkillsCategoriesRoute: typeof SkillsCategoriesRoute
  SkillsTimelineRoute: typeof SkillsTimelineRoute
  SkillsTrendingRoute: typeof SkillsTrendingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skill-growth': {
      id: '/skill-growth'
      path: '/skill-growth'
      fullPath: '/skill-growth'
      preLoaderRoute: typeof SkillGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-gap': {
      id: '/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof SkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-jobs': {
      id: '/saved-jobs'
      path: '/saved-jobs'
      fullPath: '/saved-jobs'
      preLoaderRoute: typeof SavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-insights': {
      id: '/salary-insights'
      path: '/salary-insights'
      fullPath: '/salary-insights'
      preLoaderRoute: typeof SalaryInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap-generator': {
      id: '/roadmap-generator'
      path: '/roadmap-generator'
      fullPath: '/roadmap-generator'
      preLoaderRoute: typeof RoadmapGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-completion': {
      id: '/profile-completion'
      path: '/profile-completion'
      fullPath: '/profile-completion'
      preLoaderRoute: typeof ProfileCompletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-analytics': {
      id: '/platform-analytics'
      path: '/platform-analytics'
      fullPath: '/platform-analytics'
      preLoaderRoute: typeof PlatformAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-prep': {
      id: '/interview-prep'
      path: '/interview-prep'
      fullPath: '/interview-prep'
      preLoaderRoute: typeof InterviewPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-demand': {
      id: '/industry-demand'
      path: '/industry-demand'
      fullPath: '/industry-demand'
      preLoaderRoute: typeof IndustryDemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employability': {
      id: '/employability'
      path: '/employability'
      fullPath: '/employability'
      preLoaderRoute: typeof EmployabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-progress': {
      id: '/course-progress'
      path: '/course-progress'
      fullPath: '/course-progress'
      preLoaderRoute: typeof CourseProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-success': {
      id: '/career-success'
      path: '/career-success'
      fullPath: '/career-success'
      preLoaderRoute: typeof CareerSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-forecasting': {
      id: '/career-forecasting'
      path: '/career-forecasting'
      fullPath: '/career-forecasting'
      preLoaderRoute: typeof CareerForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-dna': {
      id: '/career-dna'
      path: '/career-dna'
      fullPath: '/career-dna'
      preLoaderRoute: typeof CareerDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applied-jobs': {
      id: '/applied-jobs'
      path: '/applied-jobs'
      fullPath: '/applied-jobs'
      preLoaderRoute: typeof AppliedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/trending': {
      id: '/skills/trending'
      path: '/skills/trending'
      fullPath: '/skills/trending'
      preLoaderRoute: typeof SkillsTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/timeline': {
      id: '/skills/timeline'
      path: '/skills/timeline'
      fullPath: '/skills/timeline'
      preLoaderRoute: typeof SkillsTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/categories': {
      id: '/skills/categories'
      path: '/skills/categories'
      fullPath: '/skills/categories'
      preLoaderRoute: typeof SkillsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/assessment': {
      id: '/skills/assessment'
      path: '/skills/assessment'
      fullPath: '/skills/assessment'
      preLoaderRoute: typeof SkillsAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/add': {
      id: '/skills/add'
      path: '/skills/add'
      fullPath: '/skills/add'
      preLoaderRoute: typeof SkillsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/settings/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/subscription': {
      id: '/settings/subscription'
      path: '/settings/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/settings/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/accounts': {
      id: '/settings/accounts'
      path: '/settings/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof SettingsAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/my-courses': {
      id: '/learning/my-courses'
      path: '/learning/my-courses'
      fullPath: '/learning/my-courses'
      preLoaderRoute: typeof LearningMyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId': {
      id: '/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/job/$jobId'
      preLoaderRoute: typeof JobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  AppliedJobsRoute: AppliedJobsRoute,
  AssignmentsRoute: AssignmentsRoute,
  CareerRoute: CareerRoute,
  CareerDnaRoute: CareerDnaRoute,
  CareerForecastingRoute: CareerForecastingRoute,
  CareerSuccessRoute: CareerSuccessRoute,
  CertificatesRoute: CertificatesRoute,
  CourseProgressRoute: CourseProgressRoute,
  CoursesRoute: CoursesRoute,
  EmployabilityRoute: EmployabilityRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  IndustryDemandRoute: IndustryDemandRoute,
  InterviewPrepRoute: InterviewPrepRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PlatformAnalyticsRoute: PlatformAnalyticsRoute,
  ProfileRoute: ProfileRoute,
  ProfileCompletionRoute: ProfileCompletionRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapGeneratorRoute: RoadmapGeneratorRoute,
  SalaryInsightsRoute: SalaryInsightsRoute,
  SavedJobsRoute: SavedJobsRoute,
  SignupRoute: SignupRoute,
  SkillGapRoute: SkillGapRoute,
  SkillGrowthRoute: SkillGrowthRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CompanyCompanyIdRoute: CompanyCompanyIdRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  JobJobIdRoute: JobJobIdRoute,
  LearningMyCoursesRoute: LearningMyCoursesRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAccountsRoute: SettingsAccountsRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  SkillsAddRoute: SkillsAddRoute,
  SkillsAssessmentRoute: SkillsAssessmentRoute,
  SkillsCategoriesRoute: SkillsCategoriesRoute,
  SkillsTimelineRoute: SkillsTimelineRoute,
  SkillsTrendingRoute: SkillsTrendingRoute,
  AdminIndexRoute: AdminIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
